-- Generated by ../rebuild_design.py. Design for a NEW database, not a migration.
CREATE TABLE discovery_scans (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    seed_ip inet NOT NULL CHECK (masklen(seed_ip) IN (32, 128)),
    credential_profile_id uuid NOT NULL REFERENCES credential_profiles(id) ON DELETE RESTRICT,
    status varchar(20) NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','running','succeeded','partial','failed','cancelled')),
    timeout_seconds integer NOT NULL DEFAULT 2 CHECK (timeout_seconds > 0),
    max_depth integer NOT NULL CHECK (max_depth >= 0),
    max_devices integer NOT NULL CHECK (max_devices > 0),
    environment varchar(20) NOT NULL CHECK (environment IN ('physical','emulated')),
    initiated_by uuid,
    error_message text,
    requested_at timestamptz NOT NULL DEFAULT now(),
    started_at timestamptz,
    finished_at timestamptz,
    CHECK (started_at IS NULL OR started_at >= requested_at),
    CHECK (finished_at IS NULL OR finished_at >= COALESCE(started_at, requested_at)),
    CHECK ((status IN ('succeeded','partial','failed','cancelled')) = (finished_at IS NOT NULL)),
    CHECK (status NOT IN ('running','succeeded','partial') OR started_at IS NOT NULL)
);
CREATE INDEX idx_discovery_scans_requested_at ON discovery_scans (requested_at);
