-- Generated by ../rebuild_design.py. Design for a NEW database, not a migration.
CREATE TABLE credential_profiles (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name varchar(100) NOT NULL UNIQUE,
    username varchar(100),
    password_encrypted text,
    enable_secret_encrypted text,
    snmp_community_ro_encrypted text,
    ssh_port integer NOT NULL DEFAULT 22 CHECK (ssh_port BETWEEN 1 AND 65535),
    snmp_port integer NOT NULL DEFAULT 161 CHECK (snmp_port BETWEEN 1 AND 65535),
    description text,
    created_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((username IS NULL) = (password_encrypted IS NULL)),
    CHECK (enable_secret_encrypted IS NULL OR password_encrypted IS NOT NULL),
    CHECK (password_encrypted IS NOT NULL OR snmp_community_ro_encrypted IS NOT NULL)
);
