-- Generated by ../rebuild_design.py. Design for a NEW database, not a migration.
CREATE TABLE devices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    management_ip inet NOT NULL UNIQUE CHECK (masklen(management_ip) IN (32, 128)),
    hostname varchar(255),
    device_type varchar(20) NOT NULL DEFAULT 'unknown' CHECK (device_type IN ('router','switch','firewall','access_point','server','other','unknown')),
    role varchar(30) CHECK (role IN ('core','distribution','access','edge_router','management','other')),
    vendor varchar(50),
    model varchar(100),
    os_version varchar(100),
    serial_number varchar(100),
    chassis_id_subtype smallint CHECK (chassis_id_subtype BETWEEN 1 AND 7),
    chassis_id text,
    site_id uuid REFERENCES sites(id) ON DELETE RESTRICT,
    credential_profile_id uuid REFERENCES credential_profiles(id) ON DELETE RESTRICT,
    platform varchar(50),
    management_state varchar(20) NOT NULL DEFAULT 'active' CHECK (management_state IN ('active','maintenance','retired')),
    reachability varchar(20) NOT NULL DEFAULT 'unknown' CHECK (reachability IN ('unknown','reachable','unreachable')),
    enrollment_source varchar(30) NOT NULL CHECK (enrollment_source IN ('manual_enrollment','auto_discovery','csv_import')),
    last_seen_at timestamptz,
    reachability_checked_at timestamptz,
    last_collected_at timestamptz NOT NULL,
    uptime_seconds bigint CHECK (uptime_seconds >= 0),
    uptime_observed_at timestamptz,
    notes text,
    created_by uuid,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((chassis_id IS NULL) = (chassis_id_subtype IS NULL)),
    CHECK ((uptime_seconds IS NULL) = (uptime_observed_at IS NULL)),
    CHECK (reachability = 'unknown' OR reachability_checked_at IS NOT NULL),
    CHECK (reachability <> 'reachable' OR last_seen_at IS NOT NULL)
);
CREATE INDEX idx_devices_site_id ON devices (site_id);
CREATE INDEX idx_devices_credential_profile_id ON devices (credential_profile_id);
CREATE INDEX idx_devices_hostname ON devices (hostname);

CREATE TABLE device_group_members (
    device_id uuid NOT NULL REFERENCES devices(id) ON DELETE RESTRICT,
    group_id uuid NOT NULL REFERENCES device_groups(id) ON DELETE CASCADE,
    added_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (device_id, group_id)
);
CREATE INDEX idx_device_group_members_group_id ON device_group_members (group_id);
