-- Generated by ../rebuild_design.py. Design for a NEW database, not a migration.
CREATE TABLE device_interfaces (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id uuid NOT NULL REFERENCES devices(id) ON DELETE RESTRICT,
    if_index integer CHECK (if_index > 0),
    name varchar(255) NOT NULL,
    mac_address macaddr,
    description varchar(255),
    mode varchar(20) NOT NULL DEFAULT 'unknown' CHECK (mode IN ('access','trunk','routed','loopback','svi','unknown')),
    access_vlan_id integer CHECK (access_vlan_id BETWEEN 1 AND 4094),
    admin_status varchar(20) NOT NULL DEFAULT 'unknown' CHECK (admin_status IN ('up','down','testing','unknown')),
    oper_status varchar(20) NOT NULL DEFAULT 'unknown' CHECK (oper_status IN ('up','down','testing','unknown','dormant','not_present','lower_layer_down')),
    speed_bps bigint CHECK (speed_bps >= 0),
    collected_at timestamptz NOT NULL,
    retired_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (device_id, id),
    CHECK (access_vlan_id IS NULL OR mode = 'access')
);

CREATE TABLE interface_ip_addresses (
    interface_id uuid NOT NULL REFERENCES device_interfaces(id) ON DELETE RESTRICT,
    address inet NOT NULL,
    PRIMARY KEY (interface_id, address)
);

-- ifIndex/name may change or be reused: uniqueness applies to current interfaces only.
CREATE UNIQUE INDEX uq_interface_current_index ON device_interfaces(device_id, if_index)
    WHERE retired_at IS NULL AND if_index IS NOT NULL;
CREATE UNIQUE INDEX uq_interface_current_name ON device_interfaces(device_id, name)
    WHERE retired_at IS NULL;
